ci: Fix AWS credentials retrieval (#3613)
ci: Fix AWS credentials

Bumps the `configure-aws-credentials` action so that we no longer receive this error:

```
Assuming role with OIDC
Error: Could not assume role with OIDC: SecretAccessKey contains special characters.
```